version: 0.2
env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: 595960695514.dkr.ecr.ap-south-1.amazonaws.com

phases:
  pre_build:
    commands:
    - echo logging in to ECR...
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
    - docker build -t webapp .
    - docker tag webapp:latest $ECR_REPO/webapp:latest
    - docker push $ECR_REPO/webapp:latest
    - echo push to ECR repository
